name: CI/CD for Airflow ETL Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest

  deploy-to-ec2:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "airflow-project" ]; then
              echo "Cloning repository for the first time"
              git clone https://github.com/S-Delowar/DataFueler-automated-ETL-pipenine.git airflow-project
              cd airflow-project
            else
              echo "Repository already exists, pulling latest changes"
              cd airflow-project && git pull origin main
            fi

            echo "Check listed directories"
            ls

            echo "Initialize/update the Airflow metadata database schema"
            # (safe to re-run as it applies migrations only when needed)
            docker-compose run --rm airflow db init

            echo "Create admin user if not already created"
            docker-compose run --rm airflow users create \
              --username "${{ secrets.AIRFLOW_ADMIN_USERNAME }}" \
              --firstname "${{ secrets.AIRFLOW_ADMIN_FIRSTNAME }}" \
              --lastname "${{ secrets.AIRFLOW_ADMIN_LASTNAME }}" \
              --role Admin \
              --email "${{ secrets.AIRFLOW_ADMIN_EMAIL }}" \
              --password "${{ secrets.AIRFLOW_ADMIN_PASSWORD }}"

            echo "Stopping existing containers (if running)"
            docker-compose down

            echo "Starting Airflow services"
            docker-compose up -d



    




    


echo "Navigating to project directory"
            cd /home/ubuntu/airflow-project

            echo "Stopping existing containers"
            docker-compose down

            echo "Pulling latest changes from GitHub"
            git pull origin main

            echo "Starting Airflow services"
            docker-compose up -d